development:
  adapter: mysql2
  encoding: utf8
  database: volcanic_apps_development
  user: root
  password:
  pool: 5
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql2
  encoding: utf8
  database: volcanic_apps_production
  user: root
  password:
  pool: 5
  socket: /tmp/mysql.sock