development:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  database: apps_development
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  database: apps_test
  username: root
  password:
  pool: 5
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: apps_production
  username: apps
  host: ec2-54-216-5-67.eu-west-1.compute.amazonaws.com
  password: 4Y423gEO44ZE2zW
  pool: 5
  socket: /tmp/mysql.sock