concurrency: 25  # The number of allocated threads to process messages. Default 25
delay: 0        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - [<%=  Rails.env.development? ? 'apps-default-dev' : 'apps-default' %>, 1]